### PR TITLE
Move to CE3 & Munit

### PR DESCRIPTION
**Pull request by anthony2025**
- [x] tut -> mdoc
- [x] tests -> munit
- [x] ce2 -> ce3
- [x] scala 3
- [x] implement mapK

Test suite throwing at the end seems to be related to this: https://github.com/typelevel/munit-cats-effect/issues/110

### CODE REVIEW

**Comment by ChristopherDavenport** [comment]
Didn't realize this was a cats-effect bump.

**Comment by anthony2025** [comment]
I'ts an everything bump 🥳

**Comment by anthony2025** [comment]
I recommend squashing this one, I made a mess out of my git history.

**Comment by anthony2025** [comment]
@ChristopherDavenport finished and ready for review. Not confident in that mapK implementation since I just copied that from CE3 Semaphore.

**Review by ChristopherDavenport — APPROVED** [review]
All of this looks really strong. I have some ideas if we could not do this more efficiently with mapref since that has become more mature, but that is a problem for another day.

**Pull request merged**
